import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, PartialLangiumServices } from 'langium/lsp';
import { EntityRelationshipGeneratedModule, EntityRelationshipGeneratedSharedModule } from './generated/module.js';
import { EntityRelationshipValidator, registerValidationChecks } from './entity-relationship-validator.js';
import { DefaultElementFilter, ElkFactory, ElkLayoutEngine, IElementFilter, ILayoutConfigurator } from 'sprotty-elk';
import { LangiumSprottyServices, LangiumSprottySharedServices, SprottyDefaultModule, SprottyDiagramServices, SprottySharedModule } from 'langium-sprotty';
import { ERLayoutConfigurator } from './diagram/layout-config.js';
import { ERDiagramGenerator } from './diagram/diagram-generator.js';
const ElkConstructor = require('elkjs/lib/elk.bundled.js').default;

/**
 * Declaration of custom services - add your own service classes here.
 */
export type EntityRelationshipAddedServices = {
    validation: {
        EntityRelationshipValidator: EntityRelationshipValidator
    },
    layout: {
        ElkFactory: ElkFactory,
        ElementFilter: IElementFilter,
        LayoutConfigurator: ILayoutConfigurator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type EntityRelationshipServices = LangiumSprottyServices & EntityRelationshipAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const EntityRelationshipModule: Module<EntityRelationshipServices, PartialLangiumServices & SprottyDiagramServices & EntityRelationshipAddedServices> = {
    diagram: {
        DiagramGenerator: (services) => new ERDiagramGenerator(services),
        ModelLayoutEngine: (services) => new ElkLayoutEngine(services.layout.ElkFactory, services.layout.ElementFilter, services.layout.LayoutConfigurator) as any,
    },
    layout: {
        ElkFactory: () => () => new ElkConstructor({ algorithms: ['layered'] }),
        ElementFilter: () => new DefaultElementFilter,
        LayoutConfigurator: () => new ERLayoutConfigurator
    },
    validation: {
        EntityRelationshipValidator: () => new EntityRelationshipValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createEntityRelationshipServices(context: DefaultSharedModuleContext): {
    shared: LangiumSprottySharedServices,
    EntityRelationship: EntityRelationshipServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        EntityRelationshipGeneratedSharedModule,
        SprottySharedModule
    );
    const EntityRelationship = inject(
        createDefaultModule({ shared }),
        EntityRelationshipGeneratedModule,
        SprottyDefaultModule,
        EntityRelationshipModule
    );
    shared.ServiceRegistry.register(EntityRelationship);
    registerValidationChecks(EntityRelationship);
    return { shared, EntityRelationship };
}
